name: Node.js CI

on: [push]

env:
  USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm run build --if-present
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: $USERNAME
          password: $PASSWORD